export const ACTION_TYPE = {
	SET_SESSION: 'SET_SESSION',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	BUY_PRODUCT: 'BUY_PRODUCT',
	CLEAR_BASKET: 'CLEAR_BASKET',
	ADD_TO_BASKET: 'ADD_TO_BASKET',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
};
