export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	IS_LOADING: 'IS_LOADING',
	SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
	SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
	START_SEARCH: 'START_SEARCH',
	STOP_SEARCH: 'STOP_SEARCH',
	GET_BASKET: 'GET_BASKET',
};
